__author__ = 'pluto'


DEFAULT_PAGE_SIZE = 8


STATUS_PAYMENT_COMPLETED = 1
STATUS_PAYMENT_ROLLBACK = -1
STATUS_CHECK_COMPLETED = 2

JSON_REQUEST_HEADERS = {'content-type': 'application/json;charset=UTF-8', 'Accept': 'application/json'}

PAYMENT_TRADE_FINISHED = 'TRADE_FINISHED'
PAYMENT_TRADE_SUCCESS = 'TRADE_SUCCESS'